sudo: false
language: cpp  
before_script: 
  - git submodule update --init --recursive
  - export CXX=`which g++-4.9`
  - export CC=`which gcc-4.9`
  - mkdir build
  - gem install coveralls-lcov
install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-4.9
      - valgrind
      - mysql-client
      - sqlite3 
      - cmake-data
      - cmake
      - lcov
script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON -DMEMORY_CHECK=ON ..
  - make
  - make arg3db-coverage-info
after_success:
  - coveralls-lcov coverage.info

