language: cpp  
before_script: 
  - git submodule update --init --recursive
  - autoreconf -if
install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - valgrind
      - mysql-client
      - sqlite3 
script:
  - CXX=g++-4.8 ./configure
  - make test
  - valgrind --leak-check=full --error-exitcode=5 ./tests/arg3mysql_test
  - valgrind --leak-check=full --error-exitcode=5 ./tests/arg3sqlite_test 


