sudo: false
language: cpp
compiler: 
  - clang
  - gcc
before_script: 
  - git submodule update --init --recursive
  - mkdir build
  - gem install coveralls-lcov
install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot 
  - psql -c 'create database test;' -U postgres
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.7"; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9" GCOV="gcov-4.9"; fi
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.12.orig.tar.gz
  - tar xf lcov_1.12.orig.tar.gz
  - export PATH=$TRAVIS_BUILD_DIR/lcov-1.12/bin:$PATH  
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - clang-3.7
      - valgrind
      - libmysqlclient-dev
      - libsqlite3-dev
      - libpq-dev
      - postgresql-server-dev-all
      - cmake-data
      - cmake
services:
  - postgresql
script:
  - cd build
  - ls /usr/include/postgresql
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON -DMEMORY_CHECK=ON -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/9.5/server/catalog ..
  - make
  - make arg3db-coverage-clean
  - make test ARGS=-V
  - make arg3db-coverage-info
after_success:
  - coveralls-lcov $TRAVIS_BUILD_DIR/coverage.info

