version: '2'
services:
  test:
    build: .
    links:
      - mysql
      - postgres
    environment:
      MYSQL_URI: mysql://root:test@mysql:3306/test
      POSTGRES_URI: postgres://postgres:5432/test
    depends_on:
      - mysql
      - postgres
    command: dockerize -wait tcp://mysql:3306 -wait tcp://postgres:5432 tests/arg3db-test
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
  postgres:
    image: postgres:9.3
    environment:
      POSTGRES_DB: test
