version: '2'
services:
  test:
    image: rj_db_test
    build:
      context: .
      args:
          CMAKE_DEFINES: -DCMAKE_BUILD_TYPE=Release -DMEMORY_CHECK=ON
    links:
      - mysql
      - postgres
    privileged: true
    working_dir: /usr/src/build
    environment:
      MYSQL_URI: mysql://mysql:7878/test
      POSTGRES_URI: postgres://test:test@postgres:7979/test
    depends_on:
      - mysql
      - postgres
    command: dockerize -wait tcp://mysql:7878 -wait tcp://postgres:7979 -timeout 30s tests/rj_db_test_all
  coverage:
    image: rj_db_coverage
    build:
      context: .
      args:
          CMAKE_DEFINES: -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
    links:
      - mysql
      - postgres
    privileged: true
    working_dir: /usr/src/build
    environment:
      MYSQL_URI: mysql://mysql:7878/test
      POSTGRES_URI: postgres://test:test@postgres:7979/test
    depends_on:
      - mysql
      - postgres
    command: dockerize -wait tcp://mysql:7878 -wait tcp://postgres:7979 -timeout 30s run_coverage
  mysql:
    image: mysql
    hostname: mysql
    ports:
      - "7878:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "7979:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
