version: '2'
services:
  test:
    build: .
    links:
      - mysql
      - postgres
    privileged: true
    stdin_open: true
    working_dir: /usr/src/build
    tty: true
    environment:
      MYSQL_URI: mysql://mysql:3306/test
      POSTGRES_URI: postgres://test:test@postgres:5432/test
    depends_on:
      - mysql
      - postgres
    command: dockerize -wait tcp://mysql:3306 -wait tcp://postgres:5432 tests/rj_db-test
  mysql:
    image: mysql:5.6
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  postgres:
    image: postgres:9.3
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
